module;


#define _USE_MATH_DEFINES
#include <cmath>;
#include <vector>;
#include <iostream>;
#include <iomanip>;
#include <string_view>;
module Base.Mesh:Print;

import Base.Point;

void Print3D(std::vector<Point3D>& p_vertixs, std::string_view format)
{
    //std::cout << "this file generated by wwj's r.\n";
    for (auto& i : p_vertixs)
    {
        if (format == "table")
        {
            std::cout << std::setw(8) << i.index
                << std::setw(12) << i.x
                << std::setw(12) << i.y
                << std::setw(12) << i.z
                << "\n";
        }
    }
}