module;


#define _USE_MATH_DEFINES
#include <cmath>;
#include <vector>;
#include <iostream>;
#include <iomanip>;
#include <string_view>;
module Base.Mesh:Print;

import Base.Point;

inline void PrintPoints3D(std::vector<Point3D>& p_points, std::string_view format)
{
    //std::cout << "this file generated by wwj's r.\n";
    for (auto& i : p_points)
    {
        if (format == "table")
        {
            //如果x,y小于很小的数，则用0代替
            std::cout << std::setw(8) << i.index
                << std::setw(12) << (std::abs(i.x) <= 1e-15 ? 0 : i.x)
                << std::setw(12) << (std::abs(i.y) <= 1e-15 ? 0 : i.y)
                << std::setw(12) << i.z
                << "\n";
        }
    }
}

inline void PrintVertixs3D(std::vector<Vertixs3D>& p_vertixs, std::string_view format)
{
    //std::cout << "this file generated by wwj's r.\n";
    for (auto& i : p_vertixs)
    {
        if (format == "table")
        {
            //如果x,y小于很小的数，则用0代替
            std::cout << std::setw(8) << i.index
                << std::setw(12) << (std::abs(i.x) <= 1e-15 ? 0 : i.x)
                << std::setw(12) << (std::abs(i.y) <= 1e-15 ? 0 : i.y)
                << std::setw(12) << i.z
                << std::setw(12) << i.i
                << std::setw(12) << i.j
                << std::setw(12) << i.k
                << "\n";
        }
    }
}